security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=IBM
